services:
  # deprecated_atproto_server:
  #   container_name: bisky-server
  #   build: 
  #     context: ./server
  #     dockerfile: server.Dockerfile
  #     target: server
  #   command: "/bin/bash"
  #   stdin_open: true
  #   tty: true
  #   # command: "uvicorn ring.fast:app --proxy-headers"
  #   volumes:
  #     - ./server:/src
  #   # environment:
  #   #   - PYTHONPATH=.

  fastapi_server:
    container_name: bisky-server
    build: 
      context: .
      dockerfile: server/fastapi.Dockerfile
      target: fastapi
    command: "uv run uvicorn server.fast:app --proxy-headers"
    volumes:
      - ./server:/src/server
    environment:
      - PYTHONPATH=.
    ports:
      - "8000:8000"
  