services:
  fastapi_server:
    command: "uv run uvicorn server.fast:app --log-level debug --proxy-headers --host 0.0.0.0 --port 8004 --reload"
    volumes:
      - ./server:/src/server
      - ./data/sqlite.db:/sqlite.db